apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deploy
  labels:
    app: app1-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-temp
  template:
    metadata:
      labels:
        app: app1-temp
    spec:
      containers:
      - name: app1
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1-temp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
