apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app1
spec:
   ingressClassName: nginx
   rules:
      host: app1
      http:
         paths:
         - path: /
         backend:
            serviceName: app1
            servicePort: 80
   service:
      name: test
   port:
      number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
spec:
   ingressClassName: nginx
   rules:
      host: app2
      http:
         paths:
         - path: /
         backend:
            serviceName: app2
            servicePort: 80
   service:
      name: test
   port:
      number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app3
spec:
   ingressClassName: nginx
   rules:
      host: app3
      http:
         paths:
         - path: /
         backend:
            serviceName: app3
            servicePort: 80
   service:
      name: test
   port:
      number: 80
