Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.synced_folder ".", "/vagrant", disabled: false
	config.vm.define "fcadetS" do |s|
		s.vm.hostname = "fcadetS"
		s.vm.network "private_network", ip: "192.168.56.110"
		s.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--cpus", "4"]
			vb.customize ["modifyvm", :id, "--memory", "4096"]
			vb.customize ["modifyvm", :id, "--name", "fcadetS"]
		end
		s.vm.provision "shell", privileged: true, path: "provision.sh"
	end
end
