# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"
	config.ssh.insert_key = false

	config.vm.define "apitoiseS" do |s|
		s.vm.hostname = "apitoiseS"
		s.vm.network "private_network", ip: "192.168.56.110"
		s.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "apitoiseS"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]
			vb.customize ["modifyvm", :id, "--memory", "512"]
		end
	config.vm.provision "shell", privileged: true, path: "provision_server.sh"
	end	
	config.vm.define "apitoiseSW" do |sw|
		sw.vm.hostname = "apitoiseSW"
		sw.vm.network "private_network", ip: "192.168.56.111"
		sw.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "apitoiseSW"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]
			vb.customize ["modifyvm", :id, "--memory", "512"]
		end
	config.vm.provision "shell", privileged: true, path: "provision_worker.sh"
	end	
end
