apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: iot
  name: iot-app
spec:
  project: default
  source:
    repoURL: https://github.com/apitoise/IoT-App.git
    targetRevision: HEAD
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
